name: Dart CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
